# Generated by Django 5.2.8 on 2026-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
