# Generated by Django 5.2.8 on 2026-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
