# Generated by Django 5.2.8 on 2026-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0002_hostel_location_alter_hostel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
