# Generated by Django 5.2.8 on 2026-03-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0003_studentapplication_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='assigned_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='HostelApp.hostel'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelApp.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HostelApp.room'),
        ),
    ]
