# Generated by Django 5.2.8 on 2026-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0004_room_floor_alter_room_hostel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
