# Generated by Django 5.2.8 on 2026-05-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0005_studentapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='assigned_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HostelApp.bed'),
        ),
    ]
